global:
  postgresql:
    auth:
      username: discussions_db_username
      password: discussions_db_password
      database: discussions_db

primary:
  persistence:
    enabled: true
    size: 10Gi
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
