services:
  client:
    container_name: client
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: true
      WATCHPACK_POLLING: true
    stdin_open: true
    tty: true

  genai:
    container_name: genai
    build: 
      context: ./genai
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./genai/app/.env
    volumes:
      - ./genai:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: true
      WATCHPACK_POLLING: true
    stdin_open: true
    tty: true
