apiVersion: v1
kind: Service
metadata:
  name: team-divops-genai-service
  namespace: "genai-app"
spec:
  selector:
    app: team-divops-genai
  ports:
    - port: {{ .Values.genai.service.port }}
      targetPort: {{ .Values.genai.service.targetPort }}
      protocol: TCP
  type: {{ .Values.genai.service.type }}
