version: "3.9"

services:
  gateway-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: gateway
    env_file: .env
    volumes: [ "gatewaydata:/var/lib/postgresql/data" ]

  user-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: userService
    env_file: .env
    volumes: [ "userdata:/var/lib/postgresql/data" ]

  gateway:
    build: ./gateway
    env_file: .env
    depends_on: [ gateway-db, user-service ]
    ports: [ "8080:8080" ]

  user-service:
    build: ./user-service
    env_file: .env
    depends_on: [ user-db ]
    ports: [ "8081:8080" ]

volumes:
  gatewaydata:
  userdata: