version: '3.8'

services:
  weaviate:
    image: semitechnologies/weaviate:1.25.3
    ports:
      - "8888:8080"
      - "50051:50051"
    environment:
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - DEFAULT_VECTORIZER_MODULE=text2vec-contextionary
      - ENABLE_MODULES=text2vec-contextionary
      - CONTEXTIONARY_URL=contextionary:9999 
      - CLUSTER_HOSTNAME=node1   
    volumes:
      - weaviate-data:/var/lib/weaviate
    depends_on:
      - contextionary
    restart: always
  
  contextionary:
    image: semitechnologies/contextionary:en0.16.0-v1.0.2
    environment:
      - OCCURRENCE_WEIGHT_LINEAR_FACTOR=0.75
    ports:
      - "9999:9999"  
    restart: always

  init-schema:
    image: python:3.10-slim
    depends_on:
      - weaviate
    volumes:
      - ./vectordb_init.py:/app/vectordb_init.py:ro
    working_dir: /app
    entrypoint: >
      bash -c "
      echo '⏳ Waiting for Weaviate to become ready…';
      until curl -s http://weaviate:8080/v1/.well-known/ready | grep -q READY; do
        sleep 2;
      done;
      echo '✅ Weaviate is ready—running schema init';
      python vectordb_init.py
      "
    restart: "no"
  
  weaviate-console:
    image: semitechnologies/weaviate-console:988b502 
    ports:
      - "3000:3000"
    environment:
      - WEAVIATE_HOST=weaviate:8080
    depends_on:
      - weaviate
    restart: always

volumes:
  weaviate-data:
