version: '3.8'

services:
  weaviate:
    image: semitechnologies/weaviate:1.25.3
    ports:
      - "8888:8080"
      - "50051:50051"
    environment:
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - DEFAULT_VECTORIZER_MODULE=text2vec-contextionary
      - ENABLE_MODULES=text2vec-contextionary
      - CONTEXTIONARY_URL=contextionary:9999
      - CLUSTER_HOSTNAME=node1
      - LOG_LEVEL=info
    volumes:
      - weaviate-data:/var/lib/weaviate
    depends_on:
      contextionary:
        condition: service_started  
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/v1/.well-known/ready || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 60s  
  
  contextionary:
    image: semitechnologies/contextionary:en0.16.0-v1.0.2  
    environment:
      - OCCURRENCE_WEIGHT_LINEAR_FACTOR=0.75
      - ENABLE_COMPOUND_SPLITTING=false
    ports:
      - "9999:9999"
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:9999/.well-known/live || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 45s

  init-schema:
    image: python:3.10
    depends_on:
      weaviate:
        condition: service_healthy
    volumes:
      - ./vectordb_init.py:/app/vectordb_init.py:ro
    working_dir: /app
    environment:
      - WEAVIATE_URL=http://weaviate:8080
    command: >
      bash -c "
      echo '📦 Installing dependencies...';
      pip install --no-cache-dir requests weaviate-client==3.25.3;
      echo '⏳ Waiting additional time for Weaviate...';
      sleep 10;
      echo '🚀 Running schema initialization...';
      python vectordb_init.py
      "
    restart: "no"
  
  weaviate-console:
    image: semitechnologies/weaviate-console:latest
    ports:
      - "3000:3000"
    environment:
      - WEAVIATE_HOST=http://localhost:8888
    depends_on:
      weaviate:
        condition: service_started  
    restart: on-failure

volumes:
  weaviate-data:
    driver: local