server:
  port: 8080

spring:
  application:
    name: gateway
    profiles:
      active=dev
    data:
      redis:
        host: redis
        port: 6379
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:8081
          predicates:
            - Path=/users/**

jwt:
  secret: UIHZGZUbewg8h97IUB867863re8g7h9
  expiration-ms: 86400000 # 1h in ms

management.endpoints.web.exposure.include: '*'