apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-divops-users-service 
  namespace: "users-service"
spec:
  replicas: {{ .Values.usersService.replicaCount }}
  selector:
    matchLabels:
      app: team-divops-users-service
  template:
    metadata:
      labels:
        app: team-divops-users-service
    spec:
      containers:
        - name: users-service
          image: "{{ .Values.usersService.image.repository }}:{{ .Values.usersService.image.tag }}"
          imagePullPolicy: {{ .Values.usersService.image.pullPolicy }}
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "50m"
              memory: "50Mi"
          ports:
            - containerPort: {{ .Values.usersService.service.targetPort }}

