apiVersion: v1
kind: Service
metadata:
  name: team-divops-discussions-service
  namespace: "discussions-service"
spec:
  selector:
    app: team-divops-discussions-service
  ports:
    - port: {{ .Values.discussionsService.service.port }}
      targetPort: {{ .Values.discussionsService.service.targetPort }}
      protocol: TCP
  type: {{ .Values.discussionsService.service.type }}