{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "team-divops"
  namespace: "discussions-service"
  {{- $annotations := .Values.ingress.annotations | default dict }}
  {{- if $annotations }}
  annotations:
    {{- toYaml $annotations | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - "discussions-service.team-divops-devops25.student.k8s.aet.cit.tum.de"
      secretName: "team-divops-devops25-tls"
  {{- end }}
  rules:
    - host: "discussions-service.team-divops-devops25.student.k8s.aet.cit.tum.de"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: team-divops-discussions-service
                port:
                  number: {{ .Values.discussionsService.service.port }}
{{- end }}