namespace:
  create: false

autoscaling:
  enabled: false

genai:
  image:
    repository: ghcr.io/aet-devops25/team-divops-genai
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8000
    targetPort: 8000
  replicaCount: 1

ingress:
  enabled: true
  className: "nginx"
  tls: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
