apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-divops-client 
  namespace: "client-app"
spec:
  replicas: {{ .Values.client.replicaCount }}
  selector:
    matchLabels:
      app: team-divops-client
  template:
    metadata:
      labels:
        app: team-divops-client
    spec:
      containers:
        - name: client
          image: "{{ .Values.client.image.repository }}:{{ .Values.client.image.tag }}"
          imagePullPolicy: {{ .Values.client.image.pullPolicy }}
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "50m"
              memory: "50Mi"
          ports:
            - containerPort: {{ .Values.client.service.targetPort }}

