apiVersion: v1
kind: Service
metadata:
  name: team-divops-client-service
  namespace: "client-app"
spec:
  selector:
    app: team-divops-client
  ports:
    - port: {{ .Values.client.service.port }}
      targetPort: {{ .Values.client.service.targetPort }}
      protocol: TCP
  type: {{ .Values.client.service.type }}