apiVersion: v1
kind: Secret
metadata:
  name: genai-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  GEMINI_API_KEY: {{ .Values.secrets.GEMINI_API_KEY | quote }}
  WEAVIATE_API_KEY: {{ .Values.secrets.WEAVIATE_API_KEY | quote }}
  WEAVIATE_URL: {{ .Values.secrets.WEAVIATE_URL | quote }}
