name: Pipeline For Client Deployment

on:
  push:
    branches: [main]


env:
  KUBE_NAMESPACE: client-app
  RELEASE_NAME: team-divops-client
  HELM_CHART_PATH: ./helm/divops  # Path to your Helm chart directory
  IMAGE_NAME: ghcr.io/aet-devops25/team-divops-client:latest

jobs:
  build-and-push-client-app:
    name: Build and Push Client Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build client Docker image
        run: docker build -f ./client/Dockerfile.prod -t ${{ env.IMAGE_NAME }} ./client

      - name: Push client Docker image
        run: docker push ${{ env.IMAGE_NAME }}

  deploy-helm:
    name: Deploy Helm Chart
    runs-on: ubuntu-latest
    needs: build-and-push-client-app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'
      
      - name: Create .kube directory
        run: mkdir -p $HOME/.kube
      
      - name: Configure kubeconfig
        run: echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - name: Deploy Helm Chart
        run: helm upgrade --install ${{ env.RELEASE_NAME }} ${{ env.HELM_CHART_PATH }} --namespace ${{ env.KUBE_NAMESPACE }} --set client.image.repository=ghcr.io/aet-devops25/team-divops-client --set client.image.tag=latest --wait