name: Pipeline For Client Deployment

on:
  push:
    branches: [main]

jobs:
  build-and-push-client-app:
    name: Build and Push Client Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_NAME: ghcr.io/aet-devops25/team-divops-client:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build client Docker image
        run: docker build -f ./client/Dockerfile.prod -t $IMAGE_NAME ./client

      - name: Push client Docker image
        run: docker push $IMAGE_NAME